name: cargo-test

on:
  push:
  pull_request:

jobs:
  cargo-test:
    name: Test with `cargo test`
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
    steps:
      - name: Checkout sources (${{ matrix.toolchain }})
        uses: actions/checkout@v2

      - name: Install Rust toolchain ${{ matrix.toolchain }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          override: true # Make cargo workflows uses nightly

      - name: Check with `cargo check` on toolchain ${{ matrix.toolchain }}
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Test with `cargo test` on toolchain ${{ matrix.toolchain }}
        uses: actions-rs/cargo@v1
        with:
          command: test
